FROM custom/custom-image

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Here you can install any systems level dependencies, e.g.:
USER root
RUN apt-get update
RUN apt-get install nano -y
RUN apt-get install ffmpeg libsm6 libxext6  -y

USER airflow

# Need to create basic directories for FlowUI operations
RUN mkdir -p flowui/operators_repository
RUN mkdir -p flowui/xcom
RUN mkdir -p flowui/run_data

# Need to copy operators source code
COPY config.toml flowui/operators_repository/
COPY operators flowui/operators_repository/operators
COPY .flowui flowui/operators_repository/.flowui

# Install specific python dependencies
RUN pip install --no-cache-dir opencv-python scipy boto3